project:
  type: website
  render: 
    - "index.qmd"
    - "research.qmd"

# Meta 
description-meta: "First Bio-bytes website adapted by Daniel"
author-meta: "Dr. Daniel Flores Orozco"

website:
  title: "Bio-Bytes"
  image: images/Avatar3.png
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: solar
    toc: true

